<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <BlazorDisableThrowNavigationException>true</BlazorDisableThrowNavigationException>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\TimeMeet.Application\TimeMeet.Application.csproj" />
    <ProjectReference Include="..\TimeMeet.Infrastructure\TimeMeet.Infrastructure.csproj" />
  </ItemGroup>

	<ItemGroup>
        <PackageReference Include="Hangfire.AspNetCore" Version="1.8.25" />
        <PackageReference Include="Hangfire.PostgreSql" Version="1.21.1" />
		<PackageReference Include="MudBlazor" Version="9.11.0" />
        <PackageReference Include="Newtonsoft.Json" Version="13.0.4" />
	</ItemGroup>

</Project>
